### ISSUE TITLE
可以合作做一个，我已经完成了一大部分 https://github.com/windsome/one

### ISSUE THREAD

**Issue by windsome** [KevinOfNeu/material-design-duobao#1]
可以合作做一个，我已经完成了一大部分 <https://github.com/windsome/one>

**Comment by KevinOfNeu** [comment]
@windsome 可以啊，我先看下你的成果😊

**Comment by windsome** [comment]
源码全开放，用react，后台用koa2。这个应用我准备放在公众号中，使用微信支付，目前在等微信支付的审核，审核通过后，我会加上。

**Comment by KevinOfNeu** [comment]
@windsome 我们可以加一波Wechat？我的 ID: greg2011
